### ISSUE TITLE
This really nice RB Plugin is not compatible with current RedBeanPHP versions

### ISSUE THREAD

**Issue by sah-comp** [zewa666/RedBean_ReBean#1]
Are you still into this?

**Comment by zewa666** [comment]
hey there, sadly tbh I havent touched PHP and thus RedBean for years. If you or anybody else wants to take over this plugin I can turn over ownership or simply fork it.

**Comment by sah-comp** [comment]
Thanks for your quick answer.

I have just checked those other three forks and this one https://github.com/Grimston/RedBean_ReBean already made your plugin work with RedBeanPHP Version 5. I've justed tested it with rb-5-6-2.

**Comment by zewa666** [comment]
awesome, thx for getting back with the info. enjoy working with this great ORM, and boy would I wish something as simple and yet powerful exists over in .net and nodejs

**Comment by sah-comp** [comment]
Someone has to do .net and nodejs ;-) I hope to hammer all my forthcoming projects with RedBeanPHP, FlightPHP and some good googling.
